name: Appointments Service CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'appointments/**'
  push:
    branches: [ main ]
    paths:
      - 'appointments/**'

concurrency: 
  group: microservices-deployment
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Check for changes in the appointments service
      id: check_changes
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
          changed:
            - 'appointments/**'

    - name: Set up Docker Buildx
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to DockerHub
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./appointments
        file: ./appointments/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/appointments-service:${{ github.run_number }}

    - name: Pull the latest changes from the repository
      if: steps.check_changes.outputs.changed == 'true'
      run: git pull origin ${{ github.ref }}

    - name: Update docker-compose.yaml
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        sed -i 's|${{ secrets.DOCKERHUB_USERNAME }}/appointments-service:.*|${{ secrets.DOCKERHUB_USERNAME }}/appointments-service:${{ github.run_number }}|' docker-compose.yaml
        # Check if there are changes to commit. If there are none, the script exits with status 0.
        git diff --exit-code || {
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docker-compose.yaml
          git commit -m "Update docker-compose.yaml for appointments service to version 5"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Fetch the branch related to the pull request, check it out, and push the changes.
            git fetch origin ${{ github.head_ref }}
            git checkout -b ${{ github.head_ref }} origin/${{ github.head_ref }}
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}
          else
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
          fi
        }
