name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'doctors', 'appointments', 'frontend' ]
        include:
          - service: 'doctors'
            path: 'doctors/**'
          - service: 'appointments'
            path: 'appointments/**'
          - service: 'frontend'
            path: 'frontend/**'
    outputs:
      doctors-changed: ${{ steps.doctors_changes.outputs.changed }}
      appointments-changed: ${{ steps.appointments_changes.outputs.changed }}
      frontend-changed: ${{ steps.frontend_changes.outputs.changed }}
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Check for doctors changes
      id: doctors_changes
      if: matrix.service == 'doctors'
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
          changed:
            - 'doctors/**'

    - name: Check for appointments changes
      id: appointments_changes
      if: matrix.service == 'appointments'
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
          changed:
            - 'appointments/**'

    - name: Check for frontend changes
      id: frontend_changes
      if: matrix.service == 'frontend'
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
          changed:
            - 'frontend/**'

    - name: Set up Docker Buildx
      if: steps.${{ matrix.service }}_changes.outputs.changed == 'true'
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to DockerHub
      if: steps.${{ matrix.service }}_changes.outputs.changed == 'true'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: steps.${{ matrix.service }}_changes.outputs.changed == 'true'
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./${{ matrix.service }}
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}-service:${{ github.run_number }}

  update-compose:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: needs.build-and-push.outputs.doctors-changed == 'true' || needs.build-and-push.outputs.appointments-changed == 'true' || needs.build-and-push.outputs.frontend-changed == 'true'
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Checkout the correct branch for pull request
      if: github.event_name == 'pull_request'
      run: |
        git fetch origin ${{ github.head_ref }}
        git checkout ${{ github.head_ref }}


    - name: Pull the latest changes from the repository with rebase
      run: |
        git pull --rebase origin ${{ github.ref }}

    - name: Update docker-compose.yaml
      run: |
        if [ "${{ needs.build-and-push.outputs.doctors-changed }}" == "true" ]; then
          sed -i 's|${{ secrets.DOCKERHUB_USERNAME }}/doctors-service:.*|${{ secrets.DOCKERHUB_USERNAME }}/doctors-service:${{ github.run_number }}|' docker-compose.yaml
        fi
        if [ "${{ needs.build-and-push.outputs.appointments-changed }}" == "true" ]; then
          sed -i 's|${{ secrets.DOCKERHUB_USERNAME }}/appointments-service:.*|${{ secrets.DOCKERHUB_USERNAME }}/appointments-service:${{ github.run_number }}|' docker-compose.yaml
        fi
        if [ "${{ needs.build-and-push.outputs.frontend-changed }}" == "true" ]; then
          sed -i 's|${{ secrets.DOCKERHUB_USERNAME }}/frontend-service:.*|${{ secrets.DOCKERHUB_USERNAME }}/frontend-service:${{ github.run_number }}|' docker-compose.yaml
        fi
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docker-compose.yaml
        git commit -m "Update docker-compose.yaml"

    - name: Push changes for pull request
      if: github.event_name == 'pull_request'
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}

    - name: Push changes for direct push
      if: github.event_name != 'pull_request'
      run: |
        git push origin HEAD:${{ github.ref }} --force-with-lease
