name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'doctors', 'appointments', 'frontend' ]
        include:
          - service: 'doctors'
            path: 'doctors/**'
          - service: 'appointments'
            path: 'appointments/**'
          - service: 'frontend'
            path: 'frontend/**'
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Check for changes
      id: check_changes
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
          changed:
            - '${{ matrix.path }}'

    - name: Set up Docker Buildx
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to DockerHub
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: steps.check_changes.outputs.changed == 'true'
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./${{ matrix.service }}
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}-service:${{ github.run_number }}


    - name: Update docker-compose.yaml
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        sed -i 's|${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}-service:.*|${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}-service:${{ github.run_number }}|' ../docker-compose.yaml
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ../docker-compose.yaml
        git commit -m "Update docker-compose.yaml for ${{ matrix.service }} service"
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} ${{ github.head_ref }}
        else
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} ${{ github.ref }}
        fi
